version: '2'
services:
    pazagateway-postgresql:
        container_name: pazagateway-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/pazagateway/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=pazagateway
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
